# Generated by Django 4.1 on 2022-09-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=100, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_exercise', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description_exercise', models.CharField(max_length=500, verbose_name='Description')),
                ('correct_answer', models.CharField(blank=True, max_length=500, verbose_name='Correct answer')),
                ('image', models.URLField(blank=True, max_length=255)),
                ('available', models.BooleanField(default=True, verbose_name='Published/No Published')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishwebsite_app.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishwebsite_app.exercise_category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
