# Generated by Django 4.1 on 2022-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0002_alter_post_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='activity',
            field=models.TextField(default='none', max_length=500, verbose_name='Activity'),
            preserve_default=False,
        ),
    ]
