# Generated by Django 4.1 on 2022-09-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0003_remove_post_slug_post_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
