# Generated by Django 4.1 on 2022-09-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0004_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
