# Generated by Django 4.1 on 2022-09-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0005_remove_post_image_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
