# Generated by Django 4.1 on 2022-09-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0006_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
