# Generated by Django 4.1 on 2022-10-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('englishwebsite_app', '0008_quesmodel_post_author_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explanation_for_apply', models.CharField(max_length=255, verbose_name='Explanation')),
                ('university_title', models.ImageField(upload_to='')),
                ('professor_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProfessorApply',
                'verbose_name_plural': 'ProfessorsApply',
            },
        ),
    ]
