# Generated by Django 4.1 on 2022-09-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0008_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('short_description', models.CharField(max_length=100, verbose_name='Short description')),
                ('full_description', models.CharField(max_length=500, verbose_name='Full description')),
                ('avatar', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
    ]
