# Generated by Django 4.1 on 2022-10-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0009_professorapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
