# Generated by Django 4.1 on 2022-10-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0010_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
    ]
