# Generated by Django 4.1 on 2022-10-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0011_remove_professor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
