# Generated by Django 4.1 on 2022-10-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0012_professor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
    ]
