# Generated by Django 4.1 on 2022-10-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0013_rename_name_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
