# Generated by Django 4.1 on 2022-10-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishwebsite_app', '0014_alter_comment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
